spring:
  application:
    name: user-service


  datasource:
    url: jdbc:mysql://localhost:3307/invoice_app_user_service_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
server:
  port: 8081


logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.learn.user_service: DEBUG
